# Generated by Django 3.2.18 on 2023-05-29 06:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='postcomment',
            name='dislike_users',
            field=models.ManyToManyField(related_name='dislike_postcomments', to=settings.AUTH_USER_MODEL),
        ),
    ]
