# Generated by Django 3.2.18 on 2023-06-07 10:58

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import mountains.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crs_name', models.CharField(max_length=100)),
                ('crs_name_detail', models.CharField(max_length=255, unique=True)),
                ('distance', models.FloatField(db_column='total_distance_km')),
                ('duration', models.CharField(db_column='total_interval', max_length=255)),
                ('hidden_time', models.FloatField(db_column='total_time')),
                ('diff', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'mountains_course',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crs_name', models.CharField(max_length=100)),
                ('is_waypoint', models.BooleanField(default=False)),
                ('waypoint_name', models.CharField(max_length=50)),
                ('waypoint_category', models.CharField(db_column='category', max_length=256)),
                ('track', models.FloatField(db_column='track_se_1')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'mountains_coursedetail',
                'ordering': ['crs_name_detail', 'track'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('subname', models.CharField(max_length=200)),
                ('height', models.IntegerField()),
                ('region', models.CharField(max_length=100)),
                ('diff', models.CharField(max_length=30)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('image', models.ImageField(blank=True, upload_to=mountains.models.Mountain.image_path)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'mountains_mountain',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to=mountains.models.Review.image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('like_users', models.ManyToManyField(related_name='like_reviews', to=settings.AUTH_USER_MODEL)),
                ('mountain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mountains.mountain')),
                ('tags', models.ManyToManyField(related_name='reviews', to='mountains.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
