# Generated by Django 3.2.18 on 2023-06-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='tags',
        ),
        migrations.AddField(
            model_name='review',
            name='tags',
            field=models.ManyToManyField(related_name='reviews', to='mountains.Tag'),
        ),
    ]
