# Generated by Django 3.2.18 on 2023-06-05 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0002_auto_20230604_2313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursedetail',
            options={'managed': False, 'ordering': ['crs_name_detail', 'track']},
        ),
    ]
