# Generated by Django 3.2.18 on 2023-06-06 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0003_alter_coursedetail_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mountain',
            options={'managed': False, 'ordering': ['name']},
        ),
    ]
